apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f tester-compose.yaml
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: shale-proxy
  name: shale-proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: shale-proxy
    spec:
      containers:
      - env:
        - name: SERVERNAME
          value: matthewberryhill.com
        - name: UPSTREAM
          value: shale-tasks-api
        image: matthewberryhill/shale-proxy:3
        name: shale-proxy-proxy
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /etc/letsencrypt
          name: nginx-ssl-proxy-claim1
      restartPolicy: Always
      volumes:
      - name: nginx-ssl-proxy-claim1
        persistentVolumeClaim:
          claimName: nginx-ssl-proxy-claim1
status: {}
